# Python Programming Workshop for Beginners
### Day 2: Data Analysis
### Friday, Jan 31, 2016
### University of Waterloo
<img src="./files/party.png" width="100" \>


## Welcome!
Today's goals:
- Learn what functions are, how they are used and write our own functions
- Use functions other people created for us
    - NumPy and Matplotlib
- Analyze climate stats about Canada stored on our computer

Project: Analyze and plot data about the climate for many other countries we grab from the internet!

Slides available online at:

- uwpyb.github.io/materials/lectures

## Functions

- a piece of code we want to run often

In [5]:
def say_hello_to(name):
    print("Hello", name)

In [49]:
say_hello_to("Ivana!")
say_hello_to("everybody!")
say_hello_to("world in peace!")

Hello Ivana!
Hello everybody!
Hello world in peace!


### Counting letters in a word

In [10]:
word = 'ABSTENTIOUS'

Exercise
========
Put following lines in the right order so that the variable `length` at the end contains the number of letters in the word 'ABSTENTIOUS' 

-------
```python
1. length = length + 1
```
-------
```python
2. length = 0
```
-------
```python
3. for letter in word:
```
-------


In [7]:
def count_letters(word):
    length = 0
    for letter in word:
        length = length + 1
    return length

Exercise
========
What will each of these lines return:

```python
1. count_letters('1')
2. count_letterns('')
3. count_letters(100)
```

### Moaar functions

In [19]:
def fruit_salad(fruit1='apples',fruit2='pears',fruit3='oranges'):
    your_fruit_salad = fruit1 +' ' + fruit2 + ' ' + fruit3
    return your_fruit_salad
print(fruit_salad())

apples pears oranges


We can replace default fruits:

In [20]:
print(fruit_salad(fruit2='cherries'))

apples cherries oranges


And pass them in any order as long as we specify our fruits:

In [21]:
print(fruit_salad(fruit3='melon', fruit1='kiwi'))

kiwi pears melon


### Funtions we have used already
- `raw_input`: to store whatever user types in on the keyboard in a variable
- `type(x)`: ask Python about the data type of x
- `len(x)`: ask Python to tell us the length of a variable x

## Using functions other people wrote

<img src='./files/cake.jpg' width=500>


# NumPy
- a collection of functions (and bunch of other things) for working with numbers in Python
- numbers are stored in arrays

In [32]:
import numpy as np

numbers = np.arange(10)
print(numbers)

[0 1 2 3 4 5 6 7 8 9]


Similar handling like lists:

In [33]:
print('The first element of numbers is:', numbers[0])
print('The last element of numbers is:', numbers[-1])
print('The length of numbers is:', len(numbers))

The first element of numbers is: 0
The last element of numbers is: 9
The length of numbers is: 10


In [34]:
mean = np.mean(numbers)
smallest_element = np.min(numbers)
print('Mean:', mean)
print('Smallest element:', smallest_element)

Mean: 4.5
Smallest element: 0


Exercise
========
How would you get the largest element?

### Let's load some data from our disk

1. Create a directory called "climate" on your Desktop
2. Go here: https://github.com/uwpyb/materials/tree/master/lectures
3. Dowload two following files into your "climate" folder:
    - `can_avg_pr.csv`
    - `can_avg_temp.csv`
    
If you get stuck, raise your hand (or put a red sticky note) and a mentor will come to you!

What are these `.csv` files?
- CSV stands for comma-separated values (so we have two text files containing some data separated with commas)
- the files are average ***percipitation*** per month and average ***temperature*** per month for Canada from 1901-2009 (from http://data.worldbank.org/developers/climate-data-api)

### Let's peek into files!

### Load temperature data

In [37]:
temperatures = np.loadtxt('can_avg_temp.csv', delimiter=',', skiprows=1)

In [39]:
print(temperatures)

[[  0.         -24.66071701]
 [  1.         -23.69150162]
 [  2.         -19.1978035 ]
 [  3.         -10.45289135]
 [  4.          -0.9048363 ]
 [  5.           6.74043751]
 [  6.          10.75025368]
 [  7.           9.16687775]
 [  8.           3.31145859]
 [  9.          -4.6569581 ]
 [ 10.         -14.34275818]
 [ 11.         -21.15771103]]


Similar to the numbers before but now we don't have just one row, instead we have 12 rows and 2 colums

To get the first row:

In [40]:
temperatures[0]

array([  0.        , -24.66071701])

To get the temperature for January:

In [44]:
print('Temperature in January:', temperatures[0, 1])

Temperature in January: -24.6607170105


Exercise
========
How would you get the temperature in December?

To get all rows in the second column use `:`:

In [47]:
temperatures[:, 1]

array([-24.66071701, -23.69150162, -19.1978035 , -10.45289135,
        -0.9048363 ,   6.74043751,  10.75025368,   9.16687775,
         3.31145859,  -4.6569581 , -14.34275818, -21.15771103])

Exercise
========
Load the percipitation data stored in `can_avg_pr.csv` in a variable `percipitation`. Print the average percipitation as we have done it with the temperature.

It's good to have these numbers... but we would be able to see much more if somwhow we could nicely draw these numbers and then see month-to-month changes.

In [ ]:
# Matplotlib